app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
post_background:
    path: /Backgrounds
    defaults: {_controller: AppBundle:Background:postBackground}
    
delete_background:
    path: /Backgrounds/{id}
    defaults: {_controller: AppBundle:Background:removeBackground}
    
patch_background:
    path: /Backgrounds/{id}
    defaults: {_controller: AppBundle:Background:patchBackground}
    
post_utilisateur:
    path: /Utilisateurs
    defaults: {_controller: AppBundle:Utilisateur:postUtilisateur}
    
delete_utilisateur:
    path: /Utilisateurs/{id}
    defaults: {_controller: AppBundle:Utilisateur:removeUtilisateur}

